"""add follow, level, indexes

Revision ID: ba2d6ceb6e37
Revises: 
Create Date: 2026-05-16 21:35:12.026131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2d6ceb6e37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index('idx_follow_followed', ['followed_id'], unique=False)
        batch_op.create_index('idx_follow_follower', ['follower_id'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('idx_comment_author', ['author_id'], unique=False)
        batch_op.create_index('idx_comment_parent', ['parent_id'], unique=False)
        batch_op.create_index('idx_comment_post_status_created', ['post_id', 'status', 'created_at'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('idx_post_author_status', ['author_id', 'status'], unique=False)
        batch_op.create_index('idx_post_last_reply', ['last_reply_at'], unique=False)
        batch_op.create_index('idx_post_pinned_status', ['is_pinned', 'status'], unique=False)
        batch_op.create_index('idx_post_status_board_created', ['status', 'board_id', 'created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('exp')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('idx_post_status_board_created')
        batch_op.drop_index('idx_post_pinned_status')
        batch_op.drop_index('idx_post_last_reply')
        batch_op.drop_index('idx_post_author_status')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('idx_comment_post_status_created')
        batch_op.drop_index('idx_comment_parent')
        batch_op.drop_index('idx_comment_author')

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index('idx_follow_follower')
        batch_op.drop_index('idx_follow_followed')

    op.drop_table('follows')
    # ### end Alembic commands ###
